# Generated by Django 4.2.4 on 2023-08-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prince',
            new_name='unit_prince',
        ),
    ]
